$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: airline-endpoint
endpoint_name: airline-endpoint
model: azureml:airline-model@latest
code_configuration:
  code: ./scripts
  scoring_script: score.py
environment: 
  conda_file: ./environments/training-env.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
instance_type: Standard_DS3_v2
instance_count: 1