name: Azure ML Trigger Pipeline Sample

on:
  repository_dispatch:
    types: [deploy] 

defaults:
  run:
    working-directory: aml_yamls

permissions:
      id-token: write
      contents: read

jobs:
  job-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{secrets.AZURE_CREDENTIALS}}'
      - name: Install ML extension for az command
        run: az extension add --name ml --version 2.11.0
      - name: Create ML Job
        run: az ml online-deployment create -f managed_deployment.yml --all-traffic -g ${{secrets.AZURE_RESOURCE_GROUP_NAME}} -w ${{secrets.AZURE_ML_WORKSPACE_NAME}}